Handle conflict between dispatchers
For example:
```bash
$ cat ~/.config/swarm/config.ini
[keybindings]
show zero inventory entites = f1
$ cabal run swarm -O0 -- keybindings
Error: some key events have keys bound to them in 'Main game events' and in 'Robot panel events'
Handlers with the 'F1' binding:
  View Help screen (triggered by the event 'view help')
  Show entities with zero count in inventory (triggered by the event 'show zero inventory entites')
```